### ISSUE TITLE
Support Wazuh cluster v3.2.3

### ISSUE THREAD

**Issue by mgmacias95** [coveo/wazuh-kubernetes#5]
Hello all,

The wazuh team has released Wazuh v3.2.3 which includes some changes in the cluster:

* DNS are allowed.
* Only master IP must be specified in the configuration.
* The synchronization interval option has been removed from the configuration.
* The cluster database has been removed (`/var/ossec/var/db/cluster.db`).
* Node names are used as id, so they should be unique.
* Now there is only one cluster process running (before, there used to be 4).
* Cluster control provides a health check option which could be used for monitoring.

Check the documentation (https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html) to know more about the new cluster and don't hesitate to reach me if you need more information.

Best regards,
Marta

**Comment by sekka1** [comment]
Can we update this ask to support Wazuh 3.6.1?

**Comment by JPLachance** [comment]
Sure! I'm sorry, I'm working on many other projects and my Wazuh deployment is on hold :)

You can always fork this repository and try to upgrade to Wazuh 3.6 on your side! I did not check the changeset, but I guess it's achievable.

**Comment by sekka1** [comment]
Thank you so much for creating this in the first place =).  I am still trying to get my head around the OSSEC/wazuh world.  I have forked it and playing around with it.  It does look like the newer manager's image changed.  Like it isn't starting up everything like the version used here.  Ill update on the progress if any.

**Comment by JPLachance** [comment]
Well, looking at the diff for the image, it changed a lot since 3.2.0_6.2.1. 

https://github.com/wazuh/wazuh-docker/compare/8f40340dda573818b366945292a83adb9a1ecc15...master

I don't know what your error is, but I looking at the diff will probably help you!

**Comment by JPLachance** [comment]
@sekka1 I started working on the upgrade from Wazuh 3.2.0 to 3.6.1. You can find my code there: https://github.com/coveo/wazuh-kubernetes/tree/feature/wazuh-3.6.1/manager_cluster

Sorry, I renamed a couple of files (wazuh-client -> wazuh-worker) and made some simplifications, so the diff is messy :)

With my changes, the cluster is booting:
```bash
root@wazuh-manager-master-0:/# /var/ossec/bin/cluster_control -l
-----------------------------------------------------------------------------------------------------
Name                    Address                                                       Type    Version  
-----------------------------------------------------------------------------------------------------
wazuh-manager-master    wazuh-manager-master-0.wazuh-cluster.wazuh.svc.cluster.local  master  3.6.1    
wazuh-manager-worker-0  10.6.26.140                                                   worker  3.6.1    
wazuh-manager-worker-1  10.6.23.7                                                     worker  3.6.1    
-----------------------------------------------------------------------------------------------------
```

**Comment by JPLachance** [comment]
Hello @mgmacias95,

The PR #6 is now opened! I did my best to update the ossec.conf file (I launched the Wazuh container, looked the updated version of the file and updated mine).

I noted that the `node_name` in the `cluster` configuration must now be unique. It was not the case before. It forced me to create one ConfigMap per manager, so they can all have their unique node name. See https://github.com/coveo/wazuh-kubernetes/pull/6/files#diff-27b608b074b946870e4ddb32376337ad, I now have 3 ConfigMap:
- wazuh-manager-master-conf
- wazuh-manager-worker-0-conf
- wazuh-manager-worker-1-conf

Would it be possible to set the `$HOSTNAME` as the `node_name`? 

Being able to do
```XML
<cluster>
  <name>wazuh</name>
  <node_name>$HOSTNAME</node_name>
  <node_type>$NODE_TYPE</node_type>
  <key>some_key</key>
  <interval>10s</interval>
  <port>1516</port>
  <bind_addr>0.0.0.0</bind_addr>
  <nodes>
    <node>wazuh-manager-master-0.wazuh-cluster.wazuh.svc.cluster.local</node>
  </nodes>
  <hidden>no</hidden>
  <disabled>no</disabled>
</cluster>
```
would allow us to create only one ConfigMap that we can mount in all managers (master and worker). It would be cleaner 😄 

Anyway, great job! Changes made by the Wazuh team between 3.2 and 3.6 looks awesome!

**Comment by mgmacias95** [comment]
Hi @JPLachance,

That is a great idea! I've created an issue in wazuh's repository to work on that (https://github.com/wazuh/wazuh/issues/1329) 😄 . 

Thank you so much for your feedback!

Best regards,
Marta

**Comment by JPLachance** [comment]
Hello @mgmacias95,

Awesome! Additionally, setting the `node_type` using a `$NODE_TYPE` environment variable would allow me to use a single ConfigMap for all managers.

Would it be possible to add the support for setting `node_type` from an environment variable?

As always, thank you very much for your time 🙂 

JP

**Comment by mgmacias95** [comment]
Hello @JPLachance,

Yes! It is possible, I'm adding that to the issue as well hahaha!

Best regards,
Marta
